# Use an official Node.js image as the base
FROM node:18

# Set the working directory
# WORKDIR /workspace

# Install Expo CLI globally
# RUN npm install -g \
#     expo-cli \
#     react-native-cli
RUN npm install -g \
    eas-cli\
    expo-cli

# RUN expo install expo-dev-client
# Install Yarn (optional, for package management)
# RUN npm install -g yarn

# Install other tools or dependencies as needed
# Example: RUN apt-get update && apt-get install -y some-tool

# Expose Expo development server ports
# EXPOSE 19000 19001 19002

# # Default command to start a shell
# CMD ["bash"]